# Generated by Django 4.2 on 2023-04-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category', verbose_name='Product categories'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(verbose_name='Description of product'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='first_rate',
            field=models.IntegerField(verbose_name='Price of product'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(upload_to='auctions/images'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='lot',
            field=models.CharField(max_length=64, verbose_name='Name of product'),
        ),
    ]
