# Generated by Django 4.2 on 2023-04-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_rate_start_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catauctions', to='auctions.category', verbose_name='Product categories'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='first_rate',
            field=models.IntegerField(verbose_name='Starting price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useauctions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rate',
            name='current_rate',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='rate',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aucrates', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aucwlist', to='auctions.auction'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usewlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
