# Generated by Django 4.2 on 2023-04-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_is_active_alter_auction_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='annotation',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
