# Generated by Django 4.2 on 2023-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_comment_user_id_comment_auction_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
