# Generated by Django 4.2 on 2023-04-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auction_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
